#!/usr/bin/env python3
# NULLMAILER FORCE FROM SCRIPT

import sys
import subprocess
from email.message import EmailMessage

new_from = "FROM_REPLACE"
new_to = "TO_REPLACE"

input_str = sys.stdin.read()

subject = "sys mail"
for line in input_str.splitlines():
    if line.startswith('Subject:'):
        subject = line[len('Subject:'):]

msg = EmailMessage()
msg.set_content(input_str)
msg["Subject"] = subject
msg["From"] = new_from
msg["To"] = new_to

subprocess.run(['/usr/sbin/sendmail-bin', '-f', new_from, '-F', new_from], input=msg.as_string().encode('UTF-8'), check=True)
